Allow custom headers for request
tobilg/marathon-event-bus-client pull request #1
Opened 2017-01-18 18:45 UTC by owndann

Adding `marathonHeaders` to allow custom headers for the request this allow us to make request to the api outside the cluster or in development

2017-01-19 08:15 UTC, tobilg reviewed
Thanks for the PR! I have some small remarks, please have a look at the review comment.

2017-01-19 08:15 UTC, tobilg commented on lib/MarathonEventBusClient.js
> +    let eventSourceInitDict = self.options.marathonHeaders;
Not sure if this is a good idea here... First, the headers need to be in a `headers` property (See https://www.npmjs.com/package/eventsource#setting-http-request-headers), which I don't see in the code (usage example missing?). 

Furthermore, I'd like it better if you would have a whitelist of allowed header keys, and check if the `marathonHeaders` contains valid headers, and only using the ones which pass the whitelist.

2017-01-19 15:54 UTC, owndann commented on lib/MarathonEventBusClient.js
> +    let eventSourceInitDict = self.options.marathonHeaders;
cool that sounds good and yeah maybe didnt wrote my code right at it does not looks that i have th header property on the object but i'll change that in the next commit.

2017-01-19 16:22 UTC, tuxity commented
I'm not sure but, it should allow headers yes, but these headers in the code come from DC/OS not Marathon. That's 2 different things you have to keep in mind.

2017-01-19 17:38 UTC, owndann commented
@tuxity  @tobilg  At the time i just allow 'Authorization' and 'Content-type' on the 'marathonHeaders' property i don't know if there should be more allowedHeaders on the list

2017-01-19 17:58 UTC, tuxity requested changes

2017-01-19 17:58 UTC, tuxity commented on lib/MarathonEventBusClient.js
> +    self.allowedHeaeders = [
`self.allowedHeaders`

2017-01-19 17:58 UTC, tuxity commented on README.md
> + * `marathonHeaders`: If you are using Marathon from outside you can add options to the request. Default is an empty object `{}`.
```
* `marathonHeaders`: Allows you to add headers to Marathon's API requests. Default is an empty object `{}`.
```

2017-01-19 17:58 UTC, tuxity commented on README.md
> + Example: `marathonHeaders = {'Authorization': 'token=MARATHON_AUTH_TOKEN', 'Content-Type': 'application/json'}`
```
Example: `marathonHeaders = {'Authorization': 'token=DCOS_AUTH_TOKEN', 'Content-Type': 'application/json'}`
```

2017-01-19 17:58 UTC, tuxity commented on README.md
> +    marathonHeaders: {'Authorization': 'token=MARATHON_AUTH_TOKEN'} // if you are using the api outisde the cluster
`DCOS_AUTH_TOKEN`

2017-01-19 17:58 UTC, tuxity commented on examples/example.js
> +    marathonHeaders: { 'Authorization': 'token=MARATHON_AUTH_TOKEN'}, // if you are using the api outisde the cluster
`DCOS_AUTH_TOKEN`

2017-01-19 17:58 UTC, tuxity commented on lib/MarathonEventBusClient.js
> +     {'Authorization': 'token=MARATHON_AUTH_TOKEN', 'Content-Type': 'application/json'}
Same

2017-01-19 18:57 UTC, tobilg commented on lib/MarathonEventBusClient.js
> +    self.options.marathonHeaders = options.marathonHeaders || {};
I think this should be removed, because L60 and after

2017-01-19 19:03 UTC, tobilg commented on lib/MarathonEventBusClient.js
> +    self.options.marathonHeaders = options.marathonHeaders || {};
I think it should be

```javascript
let eventSourceInitDict = {
    headers: self.options.marathonHeaders
};
```

2017-01-20 08:13 UTC, tobilg approved these changes

2017-01-20 08:13 UTC, merged

2017-01-20 08:14 UTC, tobilg commented
Merged. I'll release a new version on npm today. Thanks @owndann @tuxity!

2017-01-20 15:50 UTC, owndann commented
@tobilg  a pleasure.

2017-01-20 16:53 UTC, tobilg commented
Version 0.1.5 has been released on npm.